import * as BlocklyNS from 'blockly/core';
/* Portable navigateur (ESM) / Node (CJS core-node.js) : sous Node l'objet complet est dans .default. */
const Blockly = BlocklyNS.Generator ? BlocklyNS : (BlocklyNS.default || BlocklyNS);

/* Définition des blocs Arduino (I/O, temps, condition). Les blocs de logique,
   boucles, maths et variables viennent de `blockly/blocks` (libraryBlocks). */
export function defineArduinoBlocks() {
  Blockly.defineBlocksWithJsonArray([
    {
      type: 'arduino_led',
      message0: 'LED intégrée %1',
      args0: [{ type: 'field_dropdown', name: 'STAT',
                options: [['allumée', 'HIGH'], ['éteinte', 'LOW']] }],
      previousStatement: null, nextStatement: null,
      colour: '#00979D',
      tooltip: 'Allume ou éteint la LED intégrée de la carte.',
    },
    {
      type: 'arduino_digital_write',
      message0: 'mettre la broche %1 à %2',
      args0: [
        { type: 'field_dropdown', name: 'PIN',
          options: [['2','2'],['3','3'],['4','4'],['5','5'],['6','6'],['7','7'],
                     ['8','8'],['9','9'],['10','10'],['11','11'],['12','12'],['13','13']] },
        { type: 'field_dropdown', name: 'STAT',
          options: [['HAUTE (HIGH)','HIGH'], ['BASSE (LOW)','LOW']] },
      ],
      previousStatement: null, nextStatement: null,
      colour: '#00979D',
      tooltip: 'Écrit HIGH ou LOW sur une broche numérique.',
    },
    {
      type: 'arduino_analog_read',
      message0: 'lire la broche analogique %1',
      args0: [{ type: 'field_dropdown', name: 'PIN',
                options: [['A0','A0'],['A1','A1'],['A2','A2'],['A3','A3'],['A4','A4'],['A5','A5']] }],
      output: null,
      colour: '#5b67c9',
      tooltip: 'Lit une valeur analogique (0-1023).',
    },
    {
      type: 'arduino_digital_read',
      message0: 'lire la broche %1',
      args0: [{ type: 'field_dropdown', name: 'PIN',
                options: [['2','2'],['3','3'],['4','4'],['5','5'],['6','6'],['7','7'],
                           ['8','8'],['9','9'],['10','10'],['11','11'],['12','12'],['13','13']] }],
      output: null,
      colour: '#5b67c9',
      tooltip: 'Lit une broche numérique (HIGH/LOW).',
    },
    {
      type: 'arduino_highlow',
      message0: '%1',
      args0: [{ type: 'field_dropdown', name: 'VAL',
                options: [['HAUTE','HIGH'], ['BASSE','LOW']] }],
      output: null,
      colour: '#5b67c9',
      tooltip: 'La valeur HIGH ou LOW.',
    },
    {
      type: 'arduino_delay',
      message0: 'attendre %1 millisecondes',
      args0: [{ type: 'field_number', name: 'MS', value: 1000, min: 0, precision: 1 }],
      previousStatement: null, nextStatement: null,
      colour: '#e7662d',
      tooltip: 'Pause en millisecondes.',
    },
    {
      type: 'arduino_if',
      message0: 'si %1 alors %2 sinon %3',
      args0: [
        { type: 'input_value', name: 'IF0' },
        { type: 'input_statement', name: 'DO0' },
        { type: 'input_statement', name: 'ELSE' },
      ],
      previousStatement: null, nextStatement: null,
      colour: '#5b67c9',
      tooltip: 'Condition complète avec une branche sinon.',
      inputsInline: true,
    },
    /* --- écriture analogique (PWM) --- */
    {
      type: 'arduino_analog_write',
      message0: 'mettre la broche %1 à la puissance %2 (PWM 0-255)',
      args0: [
        { type: 'field_dropdown', name: 'PIN',
          options: [['3','3'],['5','5'],['6','6'],['9','9'],['10','10'],['11','11']] },
        { type: 'field_number', name: 'VAL', value: 128, min: 0, max: 255, precision: 1 },
      ],
      previousStatement: null, nextStatement: null,
      colour: '#00979D',
      tooltip: 'Régule la puissance (PWM) sur les broches 3/5/6/9/10/11.',
    },
    /* --- tonalité --- */
    {
      type: 'arduino_tone',
      message0: 'jouer une tonalité sur la broche %1 à %2 Hz',
      args0: [
        { type: 'field_dropdown', name: 'PIN',
          options: [['3','3'],['5','5'],['6','6'],['9','9'],['10','10'],['11','11']] },
        { type: 'field_number', name: 'FREQ', value: 440, min: 31, max: 4000, precision: 1 },
      ],
      previousStatement: null, nextStatement: null,
      colour: '#e7662d',
      tooltip: 'Émet une tonalité (buzzer/piézo) sur une broche PWM.',
    },
    {
      type: 'arduino_notone',
      message0: 'stopper la tonalité sur la broche %1',
      args0: [{ type: 'field_dropdown', name: 'PIN',
                options: [['3','3'],['5','5'],['6','6'],['9','9'],['10','10'],['11','11']] }],
      previousStatement: null, nextStatement: null,
      colour: '#e7662d',
      tooltip: 'Arrête la tonalité en cours.',
    },
    /* --- servomoteur --- */
    {
      type: 'arduino_servo',
      message0: 'moteur servo sur la broche %1 à %2 °',
      args0: [
        { type: 'field_dropdown', name: 'PIN', options: [['9','9'],['10','10']] },
        { type: 'field_number', name: 'DEG', value: 90, min: 0, max: 180, precision: 1 },
      ],
      previousStatement: null, nextStatement: null,
      colour: '#6a2dc0',
      tooltip: 'Oriente un servomoteur (0-180°) — nécessite le brancher sur 5V/GND/signal.',
    },
    /* --- variables simples (champ de noms, adapté débutants) --- */
    {
      type: 'arduino_var_set',
      message0: 'mettre %1 à %2',
      args0: [
        { type: 'field_dropdown', name: 'VAR',
          options: [['valeur','valeur'],['x','x'],['y','y'],['compteur','compteur'],['v','v'],['t','t']] },
        { type: 'input_value', name: 'V' },
      ],
      previousStatement: null, nextStatement: null,
      colour: '#3b9c5e',
      tooltip: 'Affecte un nombre à une variable.',
    },
    {
      type: 'arduino_var_change',
      message0: 'augmenter %1 de %2',
      args0: [
        { type: 'field_dropdown', name: 'VAR',
          options: [['valeur','valeur'],['x','x'],['y','y'],['compteur','compteur'],['v','v'],['t','t']] },
        { type: 'field_number', name: 'DELTA', value: 1, precision: 1 },
      ],
      previousStatement: null, nextStatement: null,
      colour: '#3b9c5e',
      tooltip: 'Ajoute un nombre à une variable.',
    },
    {
      type: 'arduino_var_get',
      message0: '%1',
      args0: [{ type: 'field_dropdown', name: 'VAR',
                options: [['valeur','valeur'],['x','x'],['y','y'],['compteur','compteur'],['v','v'],['t','t']] }],
      output: null,
      colour: '#3b9c5e',
      tooltip: 'La valeur d\u0027une variable.',
    },
    /* --- série (débogage) --- */
    {
      type: 'arduino_serial_init',
      message0: 'démarrer la communication série à %1 bauds',
      args0: [{ type: 'field_number', name: 'BAUD', value: 9600, min: 300, max: 115200 }],
      previousStatement: null, nextStatement: null,
      colour: '#00979D',
      tooltip: 'Initialise le port série (à placer dans le programme) — ouvre la console série.',
    },
    {
      type: 'arduino_serial_print',
      message0: 'série : envoyer la ligne %1',
      args0: [{ type: 'input_value', name: 'TEXT' }],
      previousStatement: null, nextStatement: null,
      colour: '#00979D',
      tooltip: 'Envoie du texte dans la console série (Retour à la ligne).',
    },
    {
      type: 'arduino_serial_read',
      message0: 'série : lire un caractère',
      args0: [],
      output: null,
      colour: '#00979D',
      tooltip: 'Lit le prochain caractère reçu sur le port série.',
    },
    {
          type: 'arduino_serial_available',
          message0: 'série : données disponibles ?',
          args0: [],
          output: null,
          colour: '#00979D',
          tooltip: 'Vrai si des données arrivent sur le port série.',
        },
        /* --- textes --- */
        {
          type: 'arduino_text',
          message0: 'texte %1',
          args0: [{ type: 'field_input', name: 'TEXT', text: 'Bonjour' }],
          output: null,
          colour: '#a5745b',
          tooltip: 'Une chaîne de texte (à afficher sur la console série ou à comparer).',
        },
        {
          type: 'arduino_text_append',
          message0: 'ajouter le texte %1 à %2',
          args0: [
            { type: 'input_value', name: 'TEXT' },
            { type: 'field_dropdown', name: 'VAR',
              options: [['message','message'],['texte','texte'],['nom','nom'],['s','s']] },
          ],
          previousStatement: null, nextStatement: null,
          colour: '#a5745b',
          tooltip: 'Ajoute du texte à la fin de la variable texte.',
        },
        {
          type: 'arduino_text_length',
          message0: 'longueur du texte %1',
          args0: [{ type: 'input_value', name: 'TEXT' }],
          output: null,
          colour: '#a5745b',
          tooltip: 'Le nombre de caractères du texte.',
        },
        {
          type: 'arduino_text_equals',
          message0: 'texte %1 égal à %2',
          args0: [
            { type: 'input_value', name: 'A' },
            { type: 'input_value', name: 'B' },
          ],
          output: null,
          colour: '#a5745b',
          tooltip: 'Vrai si les deux textes sont identiques.',
        },
        /* --- fonctions --- */
        {
          type: 'arduino_function',
          message0: 'fonction %1 %2',
          args0: [
            { type: 'field_input', name: 'NAME', text: 'maFonction' },
            { type: 'input_statement', name: 'BODY' },
          ],
          previousStatement: null, nextStatement: null,
          colour: '#8a2be2',
          tooltip: 'Définit une fonction réutilisable (à appeler ensuite).',
        },
        {
          type: 'arduino_function_call',
          message0: 'appeler %1',
          args0: [{ type: 'field_dropdown', name: 'NAME',
                    options: [['maFonction','maFonction'],['clignoter','clignoter'],['avancer','avancer']] }],
          previousStatement: null, nextStatement: null,
          colour: '#8a2be2',
          tooltip: 'Exécute une fonction définie plus haut.',
        },
      ]);
}